const PHONE = "5492216970514";
const patientText = "Hola, quisiera solicitar un turno para una consulta de endodoncia.";
const referralText = "Hola, soy profesional y quisiera realizar una derivación para endodoncia.";
document.querySelectorAll("[data-whatsapp]").forEach((link) => { link.href = `https://wa.me/${PHONE}?text=${encodeURIComponent(patientText)}`; link.target = "_blank"; link.rel = "noreferrer"; });
document.querySelectorAll("[data-whatsapp-referral]").forEach((link) => { link.href = `https://wa.me/${PHONE}?text=${encodeURIComponent(referralText)}`; link.target = "_blank"; link.rel = "noreferrer"; });
document.getElementById("year").textContent = new Date().getFullYear();
const menuButton = document.querySelector(".menu-button");
const menu = document.getElementById("menu");
menuButton.addEventListener("click", () => { const open = menu.classList.toggle("open"); menuButton.setAttribute("aria-expanded", String(open)); });
menu.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => { menu.classList.remove("open"); menuButton.setAttribute("aria-expanded", "false"); }));
